server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/kafka_test
    username: song
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
